#!/bin/sh
#
# chkconfig: 35 99 99
# description: {{description}}
#
# Author: {{author}}
# Created: {{created}}

. /etc/rc.d/init.d/functions

PIDFILE="{{pidroot}}/{{label}}.pid"
ps -fe | grep "{{label}}" | head -n1 | cut -d" " -f 6 > ${PIDFILE}

USER="{{user}}"
DAEMON="{{execpath}}"
SCRIPT="{{script}}"
LABEL="{{label}}"
LOG_FILE="{{logroot}}/$LABEL.log"
LOCK_FILE="/var/lock/subsys/node-daemon-$LABEL"
ENV="{{env}}"

do_start()
{
  if [ ! -f "$LOCK_FILE" ] ; then
    echo -n $"Starting $LABEL: "
    runuser -l "$USER" -c "$ENV $DAEMON $SCRIPT >> $LOG_FILE &" && echo_success || echo_failure
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $LOCK_FILE
  else
    echo "$SCRIPT is locked."
    RETVAL=1
  fi
}

do_stop()
{
  echo -n $"Stopping $LABEL: "
  PID=`pgrep -f "$SCRIPT"`
  kill -9 $PID > /dev/null 2>&1 && echo_success || echo_failure
  if [ -f ${PIDFILE} ]; then
  rm ${PIDFILE}
  fi
  RETVAL=$?
  echo
  [ $RETVAL -eq 0 ] && rm -f $LOCK_FILE
}

case "$1" in
  start)
    do_start
    ;;
  stop)
    do_stop
    ;;
  restart)
    do_stop
    do_start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    RETVAL=1
esac

exit $RETVAL
